### ISSUE TITLE
srsGNB ERROR: Failed to create SCTP gateway.

### ISSUE THREAD

**Issue by rsjamwal** [srsran/srsRAN_Project_helm#1]
Getting below error while creating srsRAN gNB on K8 cluster. 
k8 running on Ubuntu 20.04.6 LTS
kernel version: 5.4.0-162-generic
CONTAINER-RUNTIME: containerd://1.7.13
K8 version: v1.28.8

root@k8-master:~/cu-du# k logs -n 5g srsran-project-cudu-chart-68f4f6c99c-l8l42

The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.

--== srsRAN gNB (commit 55c984b55) ==--

Failed to bind SCTP socket to 192.168.5.4:0. Success
srsGNB ERROR: Failed to create SCTP gateway.

Any idea what is going on ?

![Screenshot_1](https://github.com/srsran/srsRAN_Project_helm/assets/57722567/e9ca25ac-8aba-451f-aae5-d700ad7b7592)

**Comment by ninjab3s** [comment]
Hey @rsjamwal,
its seems that the CU/DU cannot bind to IP `192.168.5.4`. Can you post the output of `ip a` on the host where you run it? Thanks
