### ISSUE TITLE
Verifying the correct working of PTP helm chart

### ISSUE THREAD

**Issue by jorgebaranda** [srsran/srsRAN_Project_helm#2]
Hi SRS community,
In my attempt to test the k8s version of SRS software, I started with the PTP Helm chart. I downloaded and I modified the values.yaml to reflect the correct interfaceName*. Then, I installed and I saw the containers running but not in ready state, as you can see in the following attached file.  
[ptp_helm_logs.txt](https://github.com/user-attachments/files/15900643/ptp_helm_logs.txt)

Then, I checked the pod description and I realised about an error to pull some content, due to a missing secret.  
[ptp_describe_pod.txt](https://github.com/user-attachments/files/15900675/ptp_describe_pod.txt)

And I decided to build the container, but it gave me the following error:
[dockerfile_error.txt](https://github.com/user-attachments/files/15900684/dockerfile_error.txt)

Could you provide me some hints to properly install this Helmchart? I am not sure if it is working properly becasue the logs in the ptp_helm_logs.txt file says "port 1 (ens6f1): assuming the grand master role"

Thank you very much in advance for your time and attention,
Best regards,

*Regarding further editions values.yaml, which values should I add in the ptp_dst_mac field? Is it the MAC belonging to the "interfaceName"?)

**Comment by ninjab3s** [comment]
Hi @jorgebaranda,
the main problem in your setup is that the ptp4l client cannot find the PTP GM. I advise as a first step to get a working config for ptp4l on the bare metal host. Once you have this you can C&P it into the helm chart.

> *Regarding further editions values.yaml, which values should I add in the ptp_dst_mac field? Is it the MAC belonging to the "interfaceName"?)

This depends on the PTP profile your PTP GM is using. Can you give more insights on your setup? 
- What RU are you using? 
-  What PTP profile are you using?
- Which PTP GM do you have?
- Do you use a switch?

**Comment by ninjab3s** [comment]
Hi @jorgebaranda! 

Have all your issues been resolved? If so, lets close this issue.

Thanks!

**Comment by jorgebaranda** [comment]
Hi Nils,
Thanks for your guidance, you can close this issue. I've been able to solve it. It was a problem in my configuration.

Best regards,
Jordi
